# Generated by Django 4.2.7 on 2025-09-15 21:06

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurants", "0003_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="allergens",
            field=models.TextField(blank=True, help_text="List of allergens, separated by comma."),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="ingredients",
            field=models.TextField(blank=True, help_text="List of ingredients, separated by comma."),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="restaurants.menuitem",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="restaurants.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("menu_item__isnull", True), ("restaurant__isnull", False)),
                    models.Q(("menu_item__isnull", False), ("restaurant__isnull", True)),
                    _connector="OR",
                ),
                name="review_target_is_exclusive",
            ),
        ),
    ]
