# Generated by Django 4.2.7 on 2025-09-15 22:34

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0004_add_review_and_item_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "menu_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="inventory", to="restaurants.menuitem"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
            },
        ),
    ]
