# Generated by Django 4.2.7 on 2025-09-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0006_stockitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="allergens",
            field=models.JSONField(blank=True, default=list, help_text="List of allergens.", null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="ingredients",
            field=models.JSONField(blank=True, default=list, help_text="List of ingredients.", null=True),
        ),
    ]
