# Generated by Django 4.2.7 on 2025-09-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0008_alter_menuitem_allergens_alter_menuitem_ingredients"),
    ]

    def convert_to_json_list(apps, schema_editor):
        MenuItem = apps.get_model('restaurants', 'MenuItem')
        for item in MenuItem.objects.all():
            print(f"Processing MenuItem ID: {item.id}")
            # Convert ingredients if it's a string
            if isinstance(item.ingredients, str):
                print(f"  Ingredients (before): '{item.ingredients}' (type: {type(item.ingredients)})")
                item.ingredients = [s.strip() for s in item.ingredients.split(',') if s.strip()]
                print(f"  Ingredients (after): '{item.ingredients}' (type: {type(item.ingredients)})")
            # Convert allergens if it's a string
            if isinstance(item.allergens, str):
                print(f"  Allergens (before): '{item.allergens}' (type: {type(item.allergens)})")
                item.allergens = [s.strip() for s in item.allergens.split(',') if s.strip()]
                print(f"  Allergens (after): '{item.allergens}' (type: {type(item.allergens)})")
            item.save()

    def revert_json_list(apps, schema_editor):
        MenuItem = apps.get_model('restaurants', 'MenuItem')
        for item in MenuItem.objects.all():
            # Convert ingredients back to string
            if isinstance(item.ingredients, list):
                item.ingredients = ", ".join(item.ingredients)
            # Convert allergens back to string
            if isinstance(item.allergens, list):
                item.allergens = ", ".join(item.allergens)
            item.save()

    operations = [
        migrations.RunPython(convert_to_json_list, revert_json_list),
    ]
