# Generated by Django 5.2.6 on 2025-09-21 22:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0009_convert_ingredients_allergens_to_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="cover",
            field=models.ImageField(
                blank=True, help_text="Cover image for the menu item.", null=True, upload_to="menu_items/covers/"
            ),
        ),
        migrations.CreateModel(
            name="MenuItemMedia",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="menu_items/media/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video"), ("audio", "Audio")], max_length=10
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="media", to="restaurants.menuitem"
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
