# Generated by Django 5.2.6 on 2025-10-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0010_menuitem_cover_menuitemmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitemmedia",
            name="media_type",
            field=models.CharField(choices=[("image", "Image"), ("video", "Video")], max_length=10),
        ),
    ]
