# Generated by Django 5.2.6 on 2025-09-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_staff_user_temp_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="temp_field",
        ),
    ]
