# Generated by Django 5.2.6 on 2025-09-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_temp_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Admin"), ("RESTAURANT_OWNER", "Restaurant Owner"), ("CUSTOMER", "Customer")],
                default="CUSTOMER",
                max_length=50,
                verbose_name="User Role",
            ),
        ),
    ]
