# Generated by Django 5.2.6 on 2025-10-04 18:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0011_alter_menuitemmedia_media_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("table_number", models.CharField(max_length=50, unique=True)),
                ("capacity", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("reserved", "Reserved"),
                            ("needs_cleaning", "Needs Cleaning"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tables", to="restaurants.restaurant"
                    ),
                ),
            ],
            options={
                "ordering": ["table_number"],
                "unique_together": {("restaurant", "table_number")},
            },
        ),
    ]
