# Generated by Django 5.2.6 on 2025-10-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="qr_code_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
