name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff pytest django-stubs djangorestframework-stubs
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run Ruff Linter
      run: |
        ruff check .
    - name: Run Pyright Type Checker
      run: |
        npm install -g pyright || true # Install pyright if not found, allow failure for now
        pyright
